---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    environment: testing

platforms:
  - name: debian-7.4

suites:
  - name: shorewall-server
    driver_config:
      network:
      - ["private_network", {ip: "192.168.0.100"}]
    run_list:
      - role[shorewall-server]
